[wordpress]
wordpress-21 ansible_host=10.24.40.21
wordpress-22 ansible_host=10.24.40.22
wordpress-23 ansible_host=10.24.40.23
wordpress-24 ansible_host=10.24.40.24
wordpress-25 ansible_host=10.24.40.25
wordpress-26 ansible_host=10.24.40.26

[wordpress:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_become=true

[lxc]
wordpress-lxc-1 ansible_host=10.24.40.31
wordpress-lxc-2 ansible_host=10.24.40.32
wordpress-lxc-3 ansible_host=10.24.40.33

[lxc:vars]
ansible_user=root
ansible_password=Welkom01x
ansible_become=true

[netdata_parent]
netdata-parent ansible_host=10.24.40.10 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/id_rsa

[grafana]
grafana ansible_host=10.24.40.11 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/id_rsa ansible_become=true

[proxmox_nodes]
pve-node1 ansible_host=10.24.40.2 ansible_user=root
pve-node2 ansible_host=10.24.40.3 ansible_port=5995 ansible_user=ellaubo ansible_become_password='pannenkoekenmetstroop23$%'
pve-node3 ansible_host=10.24.40.4 ansible_port=5995 ansible_user=ellaubo ansible_become_password='pannenkoekenmetstroop23$%'

[proxmox_nodes:vars]
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_become=true

[docker_managers]
mgr1 ansible_host=10.24.40.22 ansible_user=ubuntu
mgr2 ansible_host=10.24.40.24 ansible_user=ubuntu
mgr3 ansible_host=10.24.40.26 ansible_user=ubuntu

[docker_managers:vars]
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_become=true