[wordpress]
wordpress-21 ansible_host=10.24.40.21
wordpress-22 ansible_host=10.24.40.22
wordpress-23 ansible_host=10.24.40.23
wordpress-24 ansible_host=10.24.40.24
wordpress-25 ansible_host=10.24.40.25
wordpress-26 ansible_host=10.24.40.26

[wordpress:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_become=true